### PR TITLE
Release v0.1.0 🥳

### PR DESCRIPTION
**Pull request by MiguelEmmara-ai**
Release v0.1.0

### CODE REVIEW

**Comment by MiguelEmmara-ai** [comment]
Release v0.1.0 🥳
We have come a long way!

**Comment by songexile** [comment]
Looks good to me, this is amazing!!~~~~

**Comment by Glennpgp** [comment]
I continue to be impressed by your work. Well done!

**Comment by munishk686** [comment]
This is awesome. 💀

**Pull request merged**
